CREATE TABLE IF NOT EXISTS anticheat_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    player_name VARCHAR(64) NOT NULL,
    log_message TEXT NOT NULL,
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS anticheat_bans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(80) NOT NULL UNIQUE,
    reason VARCHAR(255) NOT NULL,
    banned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
